org: natget21
app: ancona-events-api
service: ancona-events-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  profile: test
  stage: dev
  memorySize: 512
  timeout: 10
  environment:
    NODE_ENV: production
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
    AUTH0_AUDIENCE: ${env:AUTH0_AUDIENCE}
    AUTH0_CLIENT_ID: ${env:AUTH0_CLIENT_ID}
    AUTH0_CLIENT_SECRET: ${env:AUTH0_CLIENT_SECRET}
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    DB_TYPE: ${env:DB_TYPE}
    MONGODB_URI: ${env:MONGODB_URI}
    DYNAMODB_REGION: ${env:DYNAMODB_REGION}
    POSTGRES_DB: ${env:POSTGRES_DB}
    POSTGRES_USER: ${env:POSTGRES_USER}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
    POSTGRES_HOST: ${env:POSTGRES_HOST}
    STORAGE_TYPE: ${env:STORAGE_TYPE}

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 7000


iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "dynamodb:Query"
      - "dynamodb:Scan"
    Resource: "*"